runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: templates/css
- url: /.*
  script: main.app
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
